SETTINGS_PRIORITY = 0

import logging

PY3DEDITOR_LOG_FILENAME = 'py3deditor.log'
PY3DEDITOR_LOG_HANDLER_FILE_LEVEL 	 = logging.DEBUG
PY3DEDITOR_LOG_HANDLER_CONSOLE_LEVEL = logging.DEBUG


PYFORMS_LOG_FILENAME = 'pyforms.log'
PYFORMS_LOG_HANDLER_FILE_LEVEL 		= logging.DEBUG
PYFORMS_LOG_HANDLER_CONSOLE_LEVEL 	= logging.DEBUG
